#!/usr/bin/env bash
# generate-sdks.sh — pin quicktype (npm lockfile under clients/sdk/) and emit
# typed models + serializers for C#/Swift/Kotlin/TS from protocol/*.schema.json.
#
# Design (adr-20260724-protocol-message-schema-sot-rest-binding,
#         adr-20260724-sdk-codegen-quicktype-typegen):
#   - SoT = protocol/*.schema.json (NOT openapi.yaml)
#   - openapi.yaml is REST-binding annex only; transport is hand-written
#   - Deterministic: same protocol/ + pin + emit options → byte-identical models
#
# Do NOT invoke quicktype outside this wrapper (compatibility profile).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SDK_ROOT="${ROOT}/clients/sdk"
PROTOCOL="${ROOT}/protocol"
EMIT_CFG="${SDK_ROOT}/quicktype-emit.json"
PIN_FILE="${SDK_ROOT}/.quicktype-version"

if [[ ! -f "$EMIT_CFG" ]]; then
  echo "missing $EMIT_CFG" >&2
  exit 1
fi

if ! command -v npx >/dev/null 2>&1; then
  echo "npx required (Node toolchain already used by clients/ui)" >&2
  exit 1
fi

# Install pinned quicktype from clients/sdk package-lock (or package.json on first run).
(
  cd "$SDK_ROOT"
  if [[ -f package-lock.json ]]; then
    npm ci --ignore-scripts --no-audit --no-fund
  else
    npm install --ignore-scripts --no-audit --no-fund
  fi
)

# Resolve pinned version from package-lock or node_modules.
QUICKTYPE_VERSION="$(
  cd "$SDK_ROOT"
  node -e "
    const fs = require('fs');
    const lock = fs.existsSync('package-lock.json')
      ? JSON.parse(fs.readFileSync('package-lock.json','utf8'))
      : null;
    const pkg = JSON.parse(fs.readFileSync('package.json','utf8'));
    const fromLock =
      lock &&
      lock.packages &&
      (lock.packages['node_modules/quicktype'] || {}).version;
    const fromPkg = (pkg.devDependencies || {}).quicktype || '';
    const v = fromLock || fromPkg.replace(/^\\^/, '');
    if (!v) { console.error('cannot resolve quicktype version'); process.exit(1); }
    process.stdout.write(v);
  "
)"
echo "Generating SDK models with quicktype ${QUICKTYPE_VERSION}"
printf '%s\n' "$QUICKTYPE_VERSION" > "$PIN_FILE"

# Read emit config via node for reliable JSON.
mapfile -t SCHEMA_FILES < <(node -e "
  const c = require('${EMIT_CFG}');
  for (const s of c.schemas) console.log(s);
")

mapfile -t LANG_KEYS < <(node -e "
  const c = require('${EMIT_CFG}');
  for (const k of Object.keys(c.languages)) console.log(k);
")

gen_one() {
  local lang_key="$1"
  local lang out_subdir
  lang="$(node -e "const c=require('${EMIT_CFG}'); process.stdout.write(c.languages['${lang_key}'].lang)")"
  out_subdir="$(node -e "const c=require('${EMIT_CFG}'); process.stdout.write(c.languages['${lang_key}'].outSubdir)")"
  local out_dir="${SDK_ROOT}/${out_subdir}"
  mkdir -p "$out_dir"

  # Collect extra args as array.
  local -a extra=()
  while IFS= read -r arg; do
    [[ -n "$arg" ]] && extra+=("$arg")
  done < <(node -e "
    const c=require('${EMIT_CFG}');
    for (const a of (c.languages['${lang_key}'].extraArgs||[])) console.log(a);
  ")

  # One output file per schema so each language tree stays reviewable and
  # partial re-runs don't thrash unrelated models.
  for schema in "${SCHEMA_FILES[@]}"; do
    local src="${PROTOCOL}/${schema}"
    [[ -f "$src" ]] || { echo "missing schema $src" >&2; exit 1; }
    local base="${schema%.schema.json}"
    local dest
    case "$lang" in
      typescript) dest="${out_dir}/${base}.ts" ;;
      csharp)     dest="${out_dir}/${base}.cs" ;;
      kotlin)     dest="${out_dir}/${base}.kt" ;;
      swift)      dest="${out_dir}/${base}.swift" ;;
      *) echo "unsupported lang $lang" >&2; exit 1 ;;
    esac

    # top-level-type from schema file stem (Events, Commands, …).
    local top
    top="$(node -e "const s='${base}'; process.stdout.write(s.split('-').map(p=>p[0].toUpperCase()+p.slice(1)).join(''))")"

    echo "  ${lang_key}: ${schema} -> ${dest#"$SDK_ROOT"/}"
    (
      cd "$SDK_ROOT"
      # Prefer local pinned binary; fall back to npx of the locked package.
      if [[ -x node_modules/.bin/quicktype ]]; then
        QT=(node_modules/.bin/quicktype)
      else
        QT=(npx --no-install quicktype)
      fi
      # --src-lang schema: SoT is JSON Schema, not samples / openapi.
      # No wall-clock / UUID in output when options are fixed.
      "${QT[@]}" \
        --lang "$lang" \
        --src-lang schema \
        --src "$src" \
        --out "$dest" \
        --top-level "$top" \
        "${extra[@]}"
    )
  done

  # Marker so consumers know the tree is generated.
  cat > "${out_dir}/GENERATED.md" <<EOF
# Generated by scripts/generate-sdks.sh

- tool: quicktype ${QUICKTYPE_VERSION}
- source: protocol/*.schema.json (message SoT)
- openapi.yaml is **not** an input (REST-binding annex only)
- do not hand-edit; re-run \`scripts/generate-sdks.sh\`
EOF
}

for lang_key in "${LANG_KEYS[@]}"; do
  gen_one "$lang_key"
done

echo "OK: models under clients/sdk/{ts,csharp,kotlin,swift}/…/generated"
echo "    pin: clients/sdk/.quicktype-version = ${QUICKTYPE_VERSION}"
echo "    transport remains hand-written under each language tree"
